## Problem 1

In [199]:
try:
    import edgar
except ModuleNotFoundError:
    print("Module not found")

Module not found


## Problem 2

In [200]:
def div(x,y):
    assert type(x) == int , "X is not int."
    assert type(y) == int , "Y is not int."
    assert y != 0 , "Can't divide."
    return x/y

div(1,0)

AssertionError: Can't divide.

## Problem 3

In [201]:
def exemple_func(my_list:list):
    my_sum = 0
    sum_of_pairs = []
    try:
        for i in range(len(my_list)):
            sum_of_pairs.append(my_list[i] + my_list[i] + 1)
    except TypeError:
        print("Type Error")
    print("Sum of pairs:" , sum_of_pairs)

In [202]:
exemple_func([1,2,3,"asd"])

Type Error
Sum of pairs: [3, 5, 7]


## Problem 4

In [203]:
def UpperContent(filename):
    try:
        myfile = open(filename, "r")
        
        for line in myfile:
            print(line.upper())

        f.close()
    except FileNotFoundError:
        print("File not found.")
#how to check file closeing?????

In [204]:
UpperContent("list.txt")

File not found.


## Problem 5

In [205]:
import numpy as np

In [206]:
a = np.random.randint(1,10,size=(3,5))
a

array([[1, 7, 2, 3, 7],
       [5, 4, 1, 7, 6],
       [9, 4, 3, 8, 1]])

## Problem 4 (filei mej varjutyan hamarnery xarnvac en)

In [207]:
a = np.zeros(10)
a[4] = 3
print(a)

[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]


## Problem 5

In [208]:
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Problem 6

In [209]:
a = np.array([1,3,5,2,4,5])
b = a.reshape(3,2)
c = a.reshape(2,3)
print("b(3,2)=\n" , b)
print("c(2,3)=\n" , c)

b(3,2)=
 [[1 3]
 [5 2]
 [4 5]]
c(2,3)=
 [[1 3 5]
 [2 4 5]]


## Problem 7

In [210]:
def func(array):
    mijin =np.mean(array)
    while mijin > 5:
        for i in range(len(array)):
            array[i] = array[i] / 2
        mijin = np.mean(array)
    print("Mijin:" , mijin)
    print("Array:" , array)

In [211]:
a = np.array([10,30,50,20,40,50])

func(a)

Mijin: 3.8333333333333335
Array: [1 3 6 2 5 6]


## Problem 8 Cragri hamar kap chuni chapy ashxatuma cankacac chapi arrayneri het)

In [212]:
def get_column(array):
    print(array)
    columns = len(array[0])
    for i in range(columns):
        print("Column " , i , ":" , array[...,i])
        
def get_rows(array):
    print(array)
    rows = len(array)
    for i in range(rows):
        print("Row " , i , ":" , array[i,...])

In [197]:
get_rows(np.random.randint(1,10,size=(5,8)))

[[8 3 3 4 6 1 2 5]
 [1 3 4 7 5 1 7 8]
 [7 1 5 8 2 4 5 5]
 [3 5 1 8 2 5 5 9]
 [4 8 6 1 6 3 2 2]]
Row  0 : [8 3 3 4 6 1 2 5]
Row  1 : [1 3 4 7 5 1 7 8]
Row  2 : [7 1 5 8 2 4 5 5]
Row  3 : [3 5 1 8 2 5 5 9]
Row  4 : [4 8 6 1 6 3 2 2]


In [198]:
get_column(np.random.randint(1,10,size=(5,8)))

[[9 5 9 6 8 5 2 8]
 [7 4 5 8 9 2 7 6]
 [1 4 6 3 1 5 6 3]
 [9 6 2 7 1 4 4 2]
 [4 2 1 8 7 6 9 3]]
Column  0 : [9 7 1 9 4]
Column  1 : [5 4 4 6 2]
Column  2 : [9 5 6 2 1]
Column  3 : [6 8 3 7 8]
Column  4 : [8 9 1 1 7]
Column  5 : [5 2 5 4 6]
Column  6 : [2 7 6 4 9]
Column  7 : [8 6 3 2 3]
